export enum NotificationType {
    FRIEND_REQUEST_SENT = "FRIEND_REQUEST_SENT",
    FRIEND_REQUEST_ACCEPTED = "FRIEND_REQUEST_ACCEPTED",
    POST_SHARED = "POST_SHARED",
    COMMENTED_ON_POST = "COMMENTED_ON_POST",
    REPLIED_TO_COMMENT = "REPLIED_TO_COMMENT",
    POST_REACTION = "POST_REACTION",
    REACT_STORY = "REACT_STORY"
}